baseURL = "http://daryll.codes/"
languageCode = "en-us"
title = "Learn. Create. Ship."
description = "It's getting better all the time"
theme = "gohugo-theme-ananke"

[taxonomies]
  tag = 'tags'
  category = 'categories'

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = "https://twitter.com/daryllxd"
  instagram = "https://instagram.com/papsipatootie"
  youtube = ""
  github = "https://github.com/daryllxd"
  linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
